name: Docker Image build

on:
  push:
    branches: [ main ]
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch :
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  test:

    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps :
      # Checks-out your repository under $ GITHUB_WORKSPACE, so your job can access it    

   
    - uses: actions/checkout@v2
    - name : check mount
      run : ls -la
      
    - name : launch test
      run : |
          docker run -t -v `pwd`: / app / test khawla-k-banydomi / schedulerapimaster
    - name : launch tests and task manager
      run : |
          docker run -t -v `pwd`: / app / test khawla-k-banydomi / schedulerapimaster sh -c" ls -la && pwd && whoami && gulp install && gulp build && gulp test "



